### ISSUE TITLE
Animated gif on Gifts Nav 

### ISSUE THREAD

**Issue by AdenaG** [Century21Stores/UX#5]
Display Cardinal On Top of Gifts Nav in Desktop

Requirements: 
- Cardinal displays on top of logo globally at initial load, then flies to gifts lp
- Gifts nav in red font with red border, white background
- Fly only once per session
- Keep bird hovering over gifts nav for each subsequent sessions - towards left or right, not centered
- Suppress on tablet & mobile
- Suppress on sticky nav

**Comment by c21hornak** [comment]
Closing.
